fragment ArticlePage on ArticlePage {
    _metadata {
        ...PageUrl
        published
        displayName
    }
    PromoImage {
        ...ContentUrl
        ...ContentReferenceItem
    }
    Heading
    SubHeading
    Author
    Body {
        html
    }
    SeoSettings {
        ... on PageSeoSettings {
            MetaTitle
            MetaDescription
            SharingImage {
                ...ContentUrl
                ...ContentReferenceItem
            }
            GraphType
            Indexing
        }
    }
    PageAdminSettings {
        ...PageAdminSettingsProperty
    }
}
